### ISSUE TITLE
Brotab integration

### ISSUE THREAD

**Issue by kalligator** [bergercookie/awesome-albert-plugins#15]
Hello Niko, would consider a plugin integrating [brotab](https://github.com/balta2ar/brotab)? There is a ulauncher [ext for it](https://github.com/brpaz/ulauncher-brotab) that works wonderfully.
They have a folder named [albert](https://github.com/balta2ar/brotab/tree/master/brotab/albert) but I have no idea of it's purpose.

**Comment by bergercookie** [comment]
Γειά σου @kalligator :) , 

I 've just installed brotab, looks like a useful program to have.
If I like it and keep using it I will definitely add an extension for albert in this repo, but probably that won't happen in the next 1 or 2 weeks.

If you want to go ahead, feel free; I can give some guidance for adding a new albert integration.

As you mentioned they do have a plugin but it uses an older version of the albert api, specifically, prior to v0.4, so depending on your albert version, it may or may not work; All the plugins in this repo are now compatible with v0.4 and upwards.

Alternatively you can also migrate their current albert plugin to v0.4. The transition is not that hard and you can have this commit as a guide: https://github.com/bergercookie/awesome-albert-plugins/commit/2b3d4cd3f8b1f56c38ffcab8c356321100d811d1 where I'm doing thte same for my plugins

Hope this helps, let me know if you do decide to add a new extension so that we don't do double work

**Comment by justpeanuts** [comment]
Any updates on this issue?
Or is there any alternative implementation to search open Firefox browser tabs using Albert?

**Comment by kalligator** [comment]
Personally I went with ulauncher so I didn't get to follow up on this.

**Comment by balta2ar** [comment]
I've updated the included integration for the latest albert APi: https://github.com/balta2ar/brotab/tree/master/brotab/albert. Probably could do a better job installing it as well if albert is detected in the system as now one has to be installed manually.

**Comment by bergercookie** [comment]
Thanks @balta2ar .

Closing this.
