### ISSUE TITLE
Google translate plugin doesn't work

### ISSUE THREAD

**Issue by EhuddR** [bergercookie/awesome-albert-plugins#16]
Hi! I would like to inform that the plugin doesn't work in my device. I have an Arch Linux laptop. 

I've tried reinstalling the dependencies and I get the error listed in the following image.

When I go to the folder where the history.dat file should be there is nothing. I am really lost. Could you help me?

Thank you in advance 

![Screenshot_20211226_020712](https://user-images.githubusercontent.com/78237982/147401488-00000e61-8a18-47a0-9e5f-8a6611600fa3.png)

**Comment by balasopandr** [comment]
Hi @EhuddR ,
I tried to use this plugin and had this exact issue. One quick workaround I found is to manually create the desired file (just using `touch` will suffice) under `modules/google_translate/history.dat `. However, after closer inspection I found the issue is in line 52 of the plugin file. Changing `history_path.exists` to `history_path.exists()` fixes the issue. The weird thing is while the plugin now loads perfectly for me without any errors, no results are returned when requesting translation.

**Comment by bergercookie** [comment]
Hi all,

@EhuddR, apologies it took me a while to get back to you. 

Definitely the issue that @balasopandr found is a bug which I'll be fixing.

> The weird thing is while the plugin now loads perfectly for me without any errors, no results are returned when requesting translation.

It's a bit un-intuitive but, try giving it a small while e.g. half a second before pressing the last character of your query in albert.
i.e., `tr en es Hello in Spanis<pause here before pressing last char>h`

This mechanism is in place so that the plugin sends only one request to the GoogleTranslate server per  user request (and not a new one on every new keypress). This way the server won't block your IP because of suspected activity.

Part of the docs:

> To avoid getting blocked by Google, a search request is only sent when there is a 0.3 seconds difference between keystrokes. Thus, it's common when you actually want to send a request to wait a bit and then append a space character at the end of the query.

Let me know if this resolves your issue

**Comment by balasopandr** [comment]
@bergercookie thanks that worked! Which makes me a fool for not reading the docs :disappointed: . Maybe it would be more intuitive to expect a terminating character and then send the request instead of relying on typing speed/delay? Unless this is problematic for some other reason of course.  In any case, let me know if you are planning on fixing the bug or if you want me to send a PR.

**Comment by bergercookie** [comment]
> Maybe it would be more intuitive to expect a terminating character and then send the request instead of relying on typing speed/delay?

Sure, but what would that terminating character be? :-/
We could for example us `$` but you cannot guarantee that the user won't also use it as part of the request body itself

> In any case, let me know if you are planning on fixing the bug or if you want me to send a PR.

go for it :)

**Comment by EhuddR** [comment]
Thanks for the help, now it works like a charm
